# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ostrowsk/Gringo/gringo/branches/gringo2/cmake-2.6.0-Linux-i386/bin/cmake

# The command to remove a file.
RM = /home/ostrowsk/Gringo/gringo/branches/gringo2/cmake-2.6.0-Linux-i386/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /home/ostrowsk/Gringo/gringo/branches/gringo2/cmake-2.6.0-Linux-i386/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ostrowsk/Gringo/gringo/branches/gringo2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ostrowsk/Gringo/gringo/branches/gringo2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	cmake-2.6.0-Linux-i386/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	cmake-2.6.0-Linux-i386/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ostrowsk/Gringo/gringo/branches/gringo2/CMakeFiles /home/ostrowsk/Gringo/gringo/branches/gringo2/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ostrowsk/Gringo/gringo/branches/gringo2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gringo-app

# Build rule for target.
gringo-app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gringo-app
.PHONY : gringo-app

# fast build rule for target.
gringo-app/fast:
	$(MAKE) -f app/CMakeFiles/gringo-app.dir/build.make app/CMakeFiles/gringo-app.dir/build
.PHONY : gringo-app/fast

#=============================================================================
# Target rules for targets named gringo-lib

# Build rule for target.
gringo-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gringo-lib
.PHONY : gringo-lib

# fast build rule for target.
gringo-lib/fast:
	$(MAKE) -f lib/gringo/CMakeFiles/gringo-lib.dir/build.make lib/gringo/CMakeFiles/gringo-lib.dir/build
.PHONY : gringo-lib/fast

#=============================================================================
# Target rules for targets named lemon

# Build rule for target.
lemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lemon
.PHONY : lemon

# fast build rule for target.
lemon/fast:
	$(MAKE) -f lib/gringo/CMakeFiles/lemon.dir/build.make lib/gringo/CMakeFiles/lemon.dir/build
.PHONY : lemon/fast

#=============================================================================
# Target rules for targets named clasp-lib

# Build rule for target.
clasp-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clasp-lib
.PHONY : clasp-lib

# fast build rule for target.
clasp-lib/fast:
	$(MAKE) -f lib/clasp/CMakeFiles/clasp-lib.dir/build.make lib/clasp/CMakeFiles/clasp-lib.dir/build
.PHONY : clasp-lib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gringo-app"
	@echo "... gringo-lib"
	@echo "... lemon"
	@echo "... clasp-lib"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

